Repository BuyThis-DoHippo/Mapoop-FE, pull requests merged in 2025-08, with the labels that each got.

#2 [Chore] 라이브러리 설치 및 queryprovider 유틸 함수 작성
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  src/utils/ReactQueryProvider.jsx
Labels: 🔧Chore

#16 [Fix] 가게 검색 페이지 UI 수정
  src/App.jsx
  src/components/common/Filter.jsx
  src/components/common/SearchBar.jsx
  src/components/layout/Navbar.jsx
  src/mocks/mockStore.js
  src/pages/searchstore/SearchStore.jsx
Labels: 🎯Fix

#18 [Feat] 긴급찾기 페이지 구현
  src/App.jsx
  src/mocks/mockUrgent.js
  src/pages/SearchToiletUrgent.jsx
  src/pages/searchtoileturgent/MapContainer.jsx
  src/pages/searchtoileturgent/SearchToiletUrgent.jsx
Labels: ⭐FEAT

#29 [Feat] 화장실 등록 페이지 구현
  src/assets/svg/register/arrow-down.svg
  src/assets/svg/register/arrow-up.svg
  src/components/register/AddressForm.jsx
  src/components/register/DescriptionForm.jsx
  src/components/register/FacilityTags.jsx
  src/components/register/ImageUpload.jsx
  src/components/register/OperatingHours.jsx
  src/components/register/TypeSelector.jsx
  src/constants/facilityData.js
  src/hooks/useDropdown.js
  src/hooks/useRegisterToilet.js
  src/pages/registerToilet/RegisterToilet.jsx
Labels: ⭐FEAT

#57 [Feat] 화장실 등록 페이지 api 구현
  src/apis/register/registerApi.js
  src/components/register/AddressForm.jsx
  src/constants/facilityData.js
  src/hooks/register/useRegisterApi.js
  src/hooks/useRegisterToilet.js
  src/pages/registerToilet/RegisterToilet.jsx
Labels: 🔗API

#54 [Feat] 마이페이지-리뷰 관리 API 구현
  src/App.jsx
  src/apis/mypage/reviewApi.js
  src/hooks/mypage/useReviewApi.js
  src/pages/mypage/ReviewManagement.jsx
Labels: 🔗API, ⭐FEAT

#56 [Feat] 마이페이지 - 등록한 화장실 관리 API 구현
  src/App.jsx
  src/apis/mypage/toiletApi.js
  src/components/mypage/ToiletCard.jsx
  src/components/register/AddressForm.jsx
  src/hooks/mypage/useToiletApi.js
  src/hooks/useRegisterToilet.js
  src/pages/mypage/EditToilet.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/ToiletManagement.jsx
  src/pages/registerToilet/RegisterToilet.jsx
Labels: 🔗API, ⭐FEAT

#63 Fix/62 home UI
  src/pages/home/Home.jsx
Labels: 🎯Fix

#65 fix: 가게 검색, 화장실 리뷰 페이지 UI 수정
  src/pages/review/ReviewToiletlist.jsx
  src/pages/searchstore/SearchStore.jsx
Labels: 🎯Fix

#70 fix: navbar ui 수정
  src/components/layout/Navbar.jsx
Labels: 🎯Fix

#74 [Fix] mypage profile api 수정
  src/apis/mypage/profileApi.js
  src/pages/mypage/ProfileManagement.jsx
Labels: 🎯Fix
